### ISSUE TITLE
Plex Backhaul

### ISSUE THREAD

**Issue by darthShadow** [RoyXiang/plexproxy#5]
Hi,

Love the project and was wondering if you could consider adding a few ideas from https://github.com/danopia/plex-backhaul/ (Specifically: https://github.com/danopia/plex-backhaul/issues/1):

* Prefetch the next video segment of the file that's being streamed
* Multiplex Video Segments over multiple threads so that it's downloaded faster

**Comment by RoyXiang** [comment]
Hi,

I checked the source code of that repository, and it's mainly used to accelerate streaming for transcoded vidoes. Personally, I'm hosting my Plex Media Server without any transcoding, which makes me hard to do some local testing.

However, the network condition between Plex client and server is diverse, I'd prefer the streaming mechanism to be implemented on the client side personally.

Like on iOS, I use the official app and Infuse as clients, and Infuse does a better streaming when network condition becomes worse.

Anyway, pull request is welcomed, but I may not implement that feature in person.

**Comment by darthShadow** [comment]
Got it, thanks.
