### ISSUE TITLE
Infuse Proxy

### ISSUE THREAD

**Issue by darthShadow** [RoyXiang/plexproxy#6]
Hi,

Would it be possible to add a proxy for Infuse clients such that any metadata requests from Infuse to Plex can be handled via the proxy?

This can probably cache all the metadata and invalidate it based on plex server websocket messages which indicate an item update.

Something similar to what is already available for Emby & Jellyfin: https://github.com/firecore/InfuseSync

Thanks.

**Comment by RoyXiang** [comment]
Here is my use case:

1. Set [Custom server access URLs](https://support.plex.tv/articles/200430283-network/) which points to plexproxy, or some web server (e.g. Nginx) which is reverse proxying to plexproxy
2. Make that URL the only accessible URL from outside network, which means blocking incoming traffic to port `32400` or any port your PMS is using

Following these steps, any Plex clients should access PMS through plexproxy. Hope it helps :)

**Comment by RoyXiang** [comment]
Oh, I see. Indeed, I tried to add a caching layer to all metadata in the very earliest version, but failed on invalidating them in time. Maybe I need some help on that.

**Comment by darthShadow** [comment]
Do you have some code with the invalidation issues? I could give that a look and see if I can help anywhere.

**Comment by RoyXiang** [comment]
[v1.0.7](https://github.com/RoyXiang/plexproxy/blob/v1.0.7) may be the last version which implements a cache layer to metadata.

[Here](https://github.com/RoyXiang/plexproxy/blob/v1.0.7/handler/websocket.go#L72) it invalidates all the metadata on some websocket events.

And it tries to invalidate single-episode-metadata whenever it's watched/unwatched, see [plex.go#L146](https://github.com/RoyXiang/plexproxy/blob/v1.0.7/handler/plex.go#L146) and [plex.go#L363](https://github.com/RoyXiang/plexproxy/blob/v1.0.7/handler/plex.go#L363).

Anyway, it was some rough ideas and wasn't ideal, so I removed that feature in latter versions.

**Comment by darthShadow** [comment]
Perfect, thanks.

I will try to get it working and push it upstream if so.

**Comment by darthShadow** [comment]
Before I try it out, was there any specific issue that you noticed or just that the approach wasn't ideal?

**Comment by RoyXiang** [comment]
@darthShadow Hmm, it could be the invalid cache of either a watched state or some metadata attributes. I'm not so sure on that now.

**Comment by darthShadow** [comment]
Np, that helps narrow it down at least, thanks.

**Comment by darthShadow** [comment]
Closing since this probably won't be required with the upcoming direct mode: https://community.firecore.com/t/new-direct-mode-for-emby-jellyfin-and-plex/42922
